### ISSUE TITLE
Automatically remove spaces from 'class' field and replace with spaces

### ISSUE THREAD

**Issue by mikikiv** [IDXSupport/idxsupport.github.io#10]
I often don't realize that I'm copying multiple classes at once. If the form automatically replaces spaces with ',' anywhere in between words it would be super helpful. Just make sure it doesn't add a ',' to the end when there's accidentally a space

**Comment by lainvineyard** [comment]
wait a sec, the class field of the wrapper endpoint can take multiple classes like this??

**Comment by mikikiv** [comment]
If you have an element that has multiple class names, inputting a ',' between them (EX: <div class="main example middle"></div> would be "class=main,example,middle" in the URL endpoint

**Comment by lainvineyard** [comment]
I had no idea this was something the endpoint could do; I'll add this functionality in tomorrow (looking at the candidate calculator right now)

**Comment by lainvineyard** [comment]
I will fix this tonight

**Comment by lainvineyard** [comment]
closed in 7d7d8756d6f52e089e5520d8e294d66473b2d5a6
