### ISSUE TITLE
Elements are an option?

### ISSUE THREAD

**Issue by mikikiv** [IDXSupport/idxsupport.github.io#11]
I discovered that the wrapper can use an element as the target in place of an ID or Class. It doesn't come up often, but in the instances where an element is unique (like the main section of a page is <main> instead of "<div class=section main>") the Element selector will work great!

Learn more about the building of the wrapper here https://github.com/cosmicwomp/cloud-based-wrapper-system

**Comment by mikikiv** [comment]
@Fillerbit @lainvineyard 
I'll add this in right now to the options of the actual wrapper page but this could affect your automation because there is now another (while less valuable probably) option

**Comment by lainvineyard** [comment]
hmmm, this is an interesting option. some pages do use more semantic html tags like <article> so we should add this in as a feature at some point
