### ISSUE TITLE
We need node.js code to host a server for the wrapper analyzer

### ISSUE THREAD

**Issue by lainvineyard** [IDXSupport/idxsupport.github.io#2]
I already have a server, we just need to write the code. I can do this later, or if someone else wants to take a stab at it, feel free.

**Comment by lainvineyard** [comment]
Some tips for this one

1. The Express framework would be a very easy way to setup a basic server
2. The server should have a way of accepting a url string input, from an HTML form (get or post), and returning a JSON of the possible wrapper candidates by running the analysis function, sorted by rating 
3. You could move the analysis code into the server file to make things simple. 

Let me know if you have any questions. If it we're still waiting on this after a few days I'll start working on it

**Comment by Fillerbit** [comment]
Partially done https://github.com/IDXSupport/idxsupport.github.io/pull/5. Server itself is setup, anyone can modify the code to add features.

**Comment by lainvineyard** [comment]
Good job; if I have time tonight or tomorrow I'll add to it

**Comment by lainvineyard** [comment]
Basic server input/output is now implemented with 614290c34427564369637fb4d5677a4cd1de2a47
