### ISSUE TITLE
Store output of Endpoint Creator in user's browser storage

### ISSUE THREAD

**Issue by mikikiv** [IDXSupport/idxsupport.github.io#35]
When using Endpoint Creator, a log of outputs is added to the DOM after submission. It would be beneficial for users if the log is saved in the user's browser storage (memcache or something) so that they can navigate away and back to the page later and continue to see the last urls they generated.

Output should be removed from storage after 7 days by default. 

It would be super duper cool if there was a dropdown on the page that offered the user different options for the number of days this memory lasts... For example, I would set mine to like never, or 30 days since I just build a wrapper every once in a while while support members will want to clear it out more often since they potentially use the tool several times in a single day multiple days of a week.

**Comment by lainvineyard** [comment]
hmmm i think alternatively we could just write the output to a linkable file that could be shared so that the output can be provided to other users as well 

would be pretty doable

**Comment by lainvineyard** [comment]
i'll work on this when i have time unless someone wants to take this on
